services:
   _defaults:
      autoconfigure: true
      autowire: true
      public: false
      bind:
         $projectDir: '%kernel.project_dir%'
         $db: '@database_connection'
         $contentUrlGenerator: '@contao.routing.content_url_generator'
         $stringParser: '@Codefog\HasteBundle\StringParser'
         $notificationCenter: '@Terminal42\NotificationCenterBundle\NotificationCenter'
         $tokenDefinitionFactory: '@Terminal42\NotificationCenterBundle\Token\Definition\Factory\TokenDefinitionFactoryInterface'

   _instanceof:
      Contao\CoreBundle\Migration\AbstractMigration:
         tags: [ 'contao.migration' ]

   Bvs\OSIBundle\EventListener\PrepareFormDataListener:
    tags:
      - { name: 'contao.hook.prepareFormData' }
